name: CI
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    build-test:
        runs-on: ubuntu-latest
        name: Build and run tests
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        steps:
            - uses: actions/checkout@v4.0.0
            - uses: actions/setup-dotnet@v3.2.0
              with:
                  dotnet-version: 6.0.414
                  source-url: ${{ secrets.NUGET_SOURCE }}
              env:
                  NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
            - run: dotnet build -c Release
            - run: dotnet test -c Release
