name: Release and Publish

on:
    release:
        types: [ published ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            -   name: Set env
                run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - uses: actions/setup-dotnet@v3.2.0
              with:
                  dotnet-version: 6.0.414
              env:
                  NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
            - run: dotnet test -c Release
            - run: dotnet pack -c Release -o out src/WebAuthn.Net
            - run: dotnet nuget push out/WebAuthn.Net.${{ env.RELEASE_VERSION }}.nupkg --source ${{ secrets.NUGET_SOURCE }} --api-key ${{ secrets.GITHUB_TOKEN }}
